### PR TITLE
CBBD-114: Add AWS API credentials to Jenkins, for ITs that need to work with S3

### PR DESCRIPTION
**Pull request by karlmdavis**
http://issues.hhsdevcloud.us/browse/CBBD-114

This is the build *server* side of this. There's also a pull request (in the ETL project) for a build that requires this, too.

### CODE REVIEW

**Comment by karlmdavis** [comment]
Not sure if @sbrockhoff or @dho937 would like to review this? Might be interesting, if you're weird like me and into config mgmt tools. This is the update I made (and ran) to the Ansible plays that are responsible for configuring our Jenkins server. I don't do (almost) anything by hand to it -- Ansible just about runs the whole show there.

(Note that the giant encrypted chunk just contains the new credentials, along with all of the other pre-existing credentials.)

**Comment by sbrockhoff** [comment]
Looks interesting to me! I am new to Ansible so that's about all I can say about it:) One recommendation I do have, and I'm sure you have already thought about it, is to switch any personal accounts over to service accounts for Jenkins to interact with other services.

**Comment by karlmdavis** [comment]
Absolutely! Are there any personal accounts in there that you noticed? The only two I know of are for OSSRH and GitHub. For GitHub, I think the convention is for folks to use personal accounts, but a separate SSH key for them, which I've done. Unfortunately, I don't think OSSRH supports anything other than just a straight-up personal username and password.

(FWIW, for AWS, we **are** using a service account that was just created in the IDEA Lab account.)

**Comment by sbrockhoff** [comment]
Github and OSSRH I think are the 2 I noticed.
For Github, it seems like there are a few potential alternatives to using an SSH key linked to a personal account: [Managing deploy keys](https://developer.github.com/guides/managing-deploy-keys/)

For OSSRH, just did a quick google search and there are some examples out there of people creating service accounts/machine users to deploy, [like this one](https://issues.sonatype.org/browse/OSSRH-23692).

**Comment by karlmdavis** [comment]
@sbrockhoff: Excellent finds, both!

I've filed http://issues.hhsdevcloud.us/browse/CBBI-134 to address them.

**Pull request merged**
