### PR TITLE
CBBM-18: Add JIRA accounts for Curtis, Akwa, Micah, and Leena

### PR DESCRIPTION
**Pull request by karlmdavis**
http://issues.hhsdevcloud.us/browse/CBBM-18

### CODE REVIEW

**Comment by karlmdavis** [comment]
@sbrockhoff and @dho937: Another Ansible one, if you're interested in reviewing.

Personally, I **love** being able to source control stuff like this: beats the hell out of writing docs and notes that no one will ever read, and wouldn't be able to follow even if they tried.

**Comment by karlmdavis** [comment]
Unfortunately, I didn't have (or make) the time to put in place a password-change mechanism at all. ... Although... JIRA's tied to LDAP, so it might support changing passwords via LDAP... I dunno', haven't checked.

Anyways, I tell folks when I send them their account that there's unfortunately no way to modify passwords currently. And I apologize for it, because it **is** ridiculous. Sigh.

**Comment by sbrockhoff** [comment]
Understood..I just wasn't sure if this model here still allowed for password changes...and is the idea that the vault would actually update when passwords change? Or is the vault just for an initial configuration?

**Comment by karlmdavis** [comment]
Once there's a supported password change mechanism in place, the Ansible task would have to be modified to only set the password when creating accounts; never update just the password.

**Comment by sbrockhoff** [comment]
So the Ansible task will always just set passwords to an initial state then? How are the plaintext passwords stored? Or will individual users just need to keep track of their initial password even after they change it?

**Comment by karlmdavis** [comment]
> How are the plaintext passwords stored?

The passwords are pulled in from in that encrypted `vault.yml` file. Reference: http://docs.ansible.com/ansible/playbooks_vault.html

A similar mechanism that I've used on other projects is this one: https://github.com/AGWA/git-crypt. So far, Ansible Vault has provided a better user experience, though.

> So the Ansible task will always just set passwords to an initial state then? ... Or will individual users just need to keep track of their initial password even after they change it?

In pseudocode, the logic would need to look like this:

```
if(accountAlreadyExists(accountDict))
  updateAccountPropertiesExceptPassword(accountDict)
else
  createAccountAndSetInitialPassword(accountDict);
```

**Pull request merged**
